### PR TITLE
Don't nest prototype at `/prototype`

### PR DESCRIPTION
**Pull request by fofr**
Follows on from #117 

The whole repository is a prototype now, meaning we don't need to nest links at `/prototype`

Move templates out of /prototype folder and adjust routes.

### CODE REVIEW

**Review by kelliedesigner — APPROVED** [review]
LGTM

**Comment by Floppy** [comment]
I'd recommend renaming the repo to `hmpps-manage-a-sentence-in-the-community-prototype` perhaps?

**Comment by benilovj** [comment]
> I'd recommend renaming the repo to `hmpps-manage-a-sentence-in-the-community-prototype` perhaps?

Yes 👍  agreed

**Comment by fofr** [comment]
`hmpps-manage-supervisions-prototype`?

**Comment by Floppy** [comment]
Naming is problematic as HMPPS have a lot of things going on with similar names... I suspect the long one, though unwieldy, is the one we should use. But I defer to @benilovj on that.

**Comment by fofr** [comment]
I'm keen that it matches the service name: 
Screen Shot 2021-03-25 at 12 40 29

**Comment by benilovj** [comment]
> Naming is problematic as HMPPS have a lot of things going on with similar names... I suspect the long one, though unwieldy, is the one we should use. But I defer to @benilovj on that.

I don't have a preference, I'd suggest we don't stray too far from what other HMPPS teams have done

**Pull request merged**
